Insert into VMS_RULE_PARAMETERS (VRP_PARAM_ID,VRP_PARAM_NAME,VRP_PARAM_TYPE,VRP_PARAM_VALIDATION) values ('VELOCITY_CONTROL_DEVICE_COUNT','Velocity Control Device Count','5',null);

Insert into VMS_RULE_PARAM_TRANOBJ_MAPPING (VRT_PARAM_ID,VRT_DELIVERY_CHANNEL,VRT_TRAN_CODE,VRT_TRAN_OBJ_NAME) values ('VELOCITY_CONTROL_DEVICE_COUNT','16','NA','DeviceID');
Insert into VMS_RULE_PARAM_TRANOBJ_MAPPING (VRT_PARAM_ID,VRT_DELIVERY_CHANNEL,VRT_TRAN_CODE,VRT_TRAN_OBJ_NAME) values ('VELOCITY_CONTROL_DEVICE_COUNT','16','NA','PaymentApplicationInstanceID');