DECLARE
   v_chk_tab   VARCHAR2 (10);
   v_err       VARCHAR2 (1000);
   v_cnt       NUMBER (2);
BEGIN
   
	SELECT COUNT (1)
	INTO v_chk_tab
	FROM all_objects
	WHERE object_type = 'TABLE'
	AND owner = 'VMSCMS'
	AND object_name = 'VMS_FSAPI_VALIDATION_R16B1';

	IF v_chk_tab = 1
	THEN

		 
		UPDATE VMSCMS.VMS_FSAPI_VALIDATIONDTLS SET VFV_FIELD_VALUES = 'FEDEX_STANDARD_OVERNIGHT_LETTER|FEDEX_GROUND|FEDEX_STANDARD_OVERNIGHT_PACKAGE|FEDEX_TWO_DAY_PACKAGE|USPS|FEDEX_EXPEDITED_WITH_SIGNATURE|FEDEX_RUSH_WITH_SIGNATURE|UPS_GROUND|UPS_STANDARD_OVERNIGHT_PACKAGE|UPS_TWO_DAY_PACKAGE|FEDEX_INTERNATIONAL_PRIORITY|FEDEX_INTERNATIONAL_ECONOMY|FEDEX_GROUND_INTERNATIONAL' 
		WHERE VFV_API_NAME = 'ORDER' AND VFV_FIELD_NAME = 'shippingMethod'; 
			
        DBMS_OUTPUT.put_line (SQL%ROWCOUNT || ' rows Updated ');
		
 
				
   ELSE
      DBMS_OUTPUT.put_line (' Backup Object Not Found');
   END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      v_err := SUBSTR (SQLERRM, 1, 100);
      DBMS_OUTPUT.put_line ('Main Excp ' || v_err);
END;
/		 

