CREATE TABLE vmscms.CMS_KYCSTATUS_MAST_R16B6
as
SELECT * FROM vmscms.CMS_KYCSTATUS_MAST WHERE 1 = 2;

CREATE TABLE vmscms.CMS_INST_PARAM_R16B6
as
SELECT * FROM vmscms.CMS_INST_PARAM WHERE cip_param_key = 'CHARGEBACK_TIMEFRAME';