SPOOL $VMS_HOME/MAY_VMSGPRHOST_R16_RELEASE/LOG/INDEX_B4.log;

SET ECHO ON;
SET SERVEROUTPUT ON;


 
CREATE INDEX vmscms.INDX_GPRVALIDCARDSTAT_AUDITKEY 
		ON   vmscms.GPR_VALIDCARDSTAT_AUDIT ( gva_audit_key ) TABLESPACE cms_index ONLINE;


	 

SPOOL OFF;