CREATE TABLE vmscms.VMS_SHIPMENT_TRAN_MAST_R16B1
as
SELECT * FROM vmscms.VMS_SHIPMENT_TRAN_MAST WHERE 1 = 2;

CREATE TABLE vmscms.VMS_FSAPI_VALIDATION_R16B1
as
SELECT * FROM vmscms.VMS_FSAPI_VALIDATIONDTLS WHERE VFV_API_NAME = 'ORDER' AND VFV_FIELD_NAME = 'shippingMethod'; 

CREATE TABLE vmscms.VMS_PARAM_CONFIG_MAST_R16B1
as
SELECT * FROM vmscms.VMS_PARAM_CONFIG_MAST WHERE 1 = 2;

CREATE TABLE vmscms.CMS_TRANSACTION_MAST_R16B1
as
SELECT * FROM vmscms.CMS_TRANSACTION_MAST WHERE 1 = 2; 