set trimspool on

PROMPT OBJECTS CREATION STARTED

SPOOL $VMS_HOME/MIGRATION/CREATE_OBJECTS.log

SET ECHO ON
@@MIGR_DIR_PATH.sql;
SET ECHO OFF
SET SERVEROUTPUT ON
@@CREATE_DIRECTORY.sql;
SET SERVEROUTPUT OFF
SET ECHO ON
@@SEQ_MERINV_ORDR_REFRNO.sql;
@@MIGR_DIR_LIST.sql;
@@MIGR_FILE_LOAD_INFO.sql;
@@MIGR_CUST_ACCT_ERR.sql;
@@MIGR_ACCT_DATA_EXCP.sql;
@@MIGR_ACCT_DATA_TEMP.sql;
@@MIGR_CAF_INFO_ENTRY.sql;
@@MIGR_CTRL_TABLE.sql;
@@MIGR_CUST_DATA_EXCP.sql;
@@MIGR_ERROR_LOG.sql;
@@MIGR_FILE_DETL.sql;
@@MIGR_SPPRT_FUNC_DATA.sql;
@@MIGR_SPPRT_FUNC_EXCP.sql;
@@CMS_MERINV_ORDR_TEMP.sql;
@@MIGR_SUCC_LOG.sql;
@@MIGR_TRANSACTIONLOG_TEMP.sql;
@@MIGR_TXNLOG_EXCP.sql;
@@SEQ_MIGR_CALL_ID.sql;
@@MIGR_ROLL_COUNT.sql;
@@MIGR_SHRINK_SEGMENTS_LOG.sql;
@@MIGR_UPDT_CTRL_DETL.sql;
--11-OCT-2013
@@MIGR_CSR_CALLLOG_TEMP.sql;
@@MIGR_CALLOG_DATA_EXCP.sql;
--11-OCT-2013
@@CREATE_MIGR_HIST_TABLES.sql;
@@MIGR_RPT_WRT_SUCC.sql;
@@MIGR_RPT_WRT_FAIL.sql;
@@MIGR_RPT_WRT_SUCC_HIST.sql;
@@MIGR_RPT_WRT_FAIL_HIST.sql;
@@CONTROL_NUM_INSERTS.sql;
@@MIGR_HISTTBL_STATUS.sql;
-- 12-JUL-2013
@@MIGR_DET_ROLL_EXCP.sql;
--11-Aug-2013
@@MIGR_ONLINE_TXNLOG.sql;
@@MIGR_ONLINE_CARDLOG.sql;


SET ECHO OFF
@@SP_MIGR_FILE_DETL.prc;
@@SP_GET_DIR_LIST.prc;
@@SP_MIGR_FILE_LOAD_INFO.prc;
@@SP_MIGR_LOG_EXCP_ACCOUNTDATA.prc;
@@SP_MIGR_LOG_EXCP_CUSTDATA.prc;
@@SP_MIGR_LOG_EXCP_SPPRTFUNC.prc;
@@SP_MIGR_LOG_EXCP_TXNS.prc;
--@@MIGR_ENTRY_NEWCAF_PKG.pks;
@@MIGR_ACCT_DATA_LOAD.prc;
@@MIGR_CUST_DATA_LOAD.prc;
@@MIGR_SPPRT_FUNC_DATA_LOAD.prc;
@@MIGR_TXNLOG_DATA_LOAD.prc;
@@SP_MERINV_ORDER_CHECK.prc;
--11-OCT-2013
@@SP_MIGR_LOG_EXCP_CALLOGDATA.prc;
@@MIGR_CALLLOG_DATA_LOAD.prc;
--11-OCT-2013

-- 12-JUL-2013
@@MIG_SEQ_NO.sql;
@@MIGR_GEN_DATA_LOAD.prc;
@@MIGR_SHRINK_SEGMENTS.prc;
@@MIGR_BULK_SHRINK_SEGMENT.prc;
--@@MIGR_ROLLBACK_PROC.prc;
@@SP_ACCT_TMPNO.prc;
@@MIGR_FIND_BINPREFIX.prc;
@@SP_PANACCT_CTRL_UPDT.prc;
@@MIGR_TRAN_DETL_EXCP_REP.prc;
@@MIGR_DETAIL_EXCP_TRAN_LOAD_REP.prc;
@@MIGR_TRAN_FILEWISE_LOAD_SUMRY.prc;
@@MIGR_TRAN_FILE_LOAD_EXCP.prc;
@@MIGR_TRAN_FILE_LOAD_SUCC.prc;
@@MIGR_CUST_FILE_LOAD_SUCC.prc;
@@MIGR_CUST_FILE_LOAD_EXCP.prc;
@@MIGR_CUST_FILEWISE_LOAD_SUMRY.prc;
@@MIGR_DETAIL_EXCP_CUST_LOAD_REP.prc;
@@MIGR_CUST_CARD_DATA_SUMRY_REP.prc;
@@MIGR_TRAN_DATA_SUMRY_REP.prc;
@@MIGR_ACCT_SUCC_DETL_REP.prc;
@@MIGR_CUST_SUCC_DETL_REP.prc;
@@MIGR_CUST_EXCP_DETL_REP.prc;
@@MIGR_TRAN_SUCCESS_DETAIL_REP.prc;
@@MIGR_ACCO_FILE_LOAD_EXCP.prc;
@@MIGR_ACCO_FILE_LOAD_SUCC.prc;
@@MIGR_ACCO_FILEWISE_LOAD_SUMRY.prc;
@@MIGR_DETAIL_EXCP_ACCT_LOAD_REP.prc;
@@MIGR_DETAIL_EXCP_ACCT_REP.prc;
-- 12-JUL-2013
@@MIGR_FILE_ROLL_INFO.prc;
@@SP_MIGR_ROLLBACK.prc;
--11-Aug-2013
@@MIGR_ONLINE_TXNDATA_FILE.prc;
@@MIGR_ONLINE_CARDDATA_FILE.prc;
@@MIGR_ONLINE_ACCTDATA_FILE.prc;
@@MIGR_ONLINE_TXNDATA_AFTMIG.prc;
@@MIGR_ONLINE_CARDDATA_AFTMIG.prc;
@@MIGR_ROLL_CARD_DATA_SUMRY_REP.prc;
@@MIGR_ROLL_TRAN_DATA_SUMRY_REP.prc;
@@MIGR_ROLL_ACCT_DATA_SUMRY_REP.prc;
@@MIGR_ROLL_DETL_EXCP_REP.prc;
--11-OCT-2013
@@MIGR_CALL_DATA_SUMRY_REP.prc;
@@MIGR_CALL_EXCP_DETL_REP.prc;
@@MIGR_CALL_FILE_LOAD_EXCP.prc;
@@MIGR_CALL_FILE_LOAD_SUCC.prc;
@@MIGR_CALL_FILEWISE_LOAD_SUMRY.prc;
@@MIGR_CALL_SUCC_DETL_REP.prc;
@@MIGR_DETAIL_EXCP_CALL_LOAD_REP.prc;
@@MIGR_ROLL_CALL_DATA_SUMRY_REP.prc;
-- added 28 Oct 2013
--@@alter_tab.sql;
@@MIGR_ENTRY_NEWCAF_PKG.pks;

SPOO OFF;

PROMPT OBJECTS CREATION COMPLETED
