PROMPT 		CONTROL NUMBER UPDATE ACTIVITY STARTED

SPOOL $VMS_HOME/MIGRATION/CONTROL_NUMB_UPDATE.log
SET ECHO OFF
--SET SERVEROUTPUT ON

--@$VMS_HOME/MIGRATION/SOURCE/MOVE_TO_MIGR_HIST_TAB.sql

--@$VMS_HOME/MIGRATION/SOURCE/CUSTCODE_UPDT.sql;   

--@$VMS_HOME/MIGRATION/SOURCE/ACCTID_UPDT.sql;

--@$VMS_HOME/MIGRATION/SOURCE/ADDRCODE_UPDT.sql;

@$VMS_HOME/MIGRATION/SOURCE/APPLCODE_UPDT.sql;

--@$VMS_HOME/MIGRATION/SOURCE/ROWID_UPDT.sql;

--@$VMS_HOME/MIGRATION/SOURCE/CUSTID_UPDT.sql;
--SET SERVEROUTPUT OFF
COMMIT;
 
SPOOL OFF;

PROMPT 		CONTROL NUMBER UPDATE ACTIVITY COMPLETED
