PROMPT      GENERATING ROLLBACK DATA REPORTS   

EXECUTE VMSCMS.MIGR_ROLL_ACCT_DATA_SUMRY_REP;
EXECUTE VMSCMS.MIGR_ROLL_CARD_DATA_SUMRY_REP;
EXECUTE VMSCMS.MIGR_ROLL_TRAN_DATA_SUMRY_REP;
EXECUTE VMSCMS.MIGR_ROLL_DETL_EXCP_REP;

PROMPT      DATA ROLLBACK REPORTS GENERATION COMPLETED   

