PROMPT      GENERATING DATA LOAD REPORTS   

EXECUTE VMSCMS.MIGR_DETAIL_EXCP_ACCT_LOAD_REP;
EXECUTE VMSCMS.MIGR_DETAIL_EXCP_CUST_LOAD_REP;
EXECUTE VMSCMS.MIGR_DETAIL_EXCP_TRAN_LOAD_REP;
EXECUTE VMSCMS.MIGR_ACCO_FILE_LOAD_EXCP;
EXECUTE VMSCMS.MIGR_ACCO_FILE_LOAD_SUCC;
EXECUTE VMSCMS.MIGR_ACCO_FILEWISE_LOAD_SUMRY;
EXECUTE VMSCMS.MIGR_CUST_FILE_LOAD_EXCP;
EXECUTE VMSCMS.MIGR_CUST_FILE_LOAD_SUCC;
EXECUTE VMSCMS.MIGR_CUST_FILEWISE_LOAD_SUMRY;
EXECUTE VMSCMS.MIGR_TRAN_FILE_LOAD_EXCP;
EXECUTE VMSCMS.MIGR_TRAN_FILE_LOAD_SUCC;
EXECUTE VMSCMS.MIGR_TRAN_FILEWISE_LOAD_SUMRY;

EXECUTE VMSCMS.MIGR_DETAIL_EXCP_CALL_LOAD_REP;
EXECUTE VMSCMS.MIGR_CALL_FILE_LOAD_EXCP;
EXECUTE VMSCMS.MIGR_CALL_FILE_LOAD_SUCC;
EXECUTE VMSCMS.MIGR_CALL_FILEWISE_LOAD_SUMRY;

COMMIT;

PROMPT      DATA LOAD REPORTS GENERATION COMPLETED

--@@DETAIL_EXCP_ACCT_LOAD_REP.sql;
--@@DETAIL_EXCP_CUST_LOAD_REP.sql;
--@@DETAIL_EXCP_TRAN_LOAD_REP.sql;
--@@ACCO_FILE_LOAD_EXCP.sql;
--@@ACCO_FILE_LOAD_SUCC.sql;
--@@ACCO_FILE_REC_CNT.sql;
--@@CUST_FILE_LOAD_EXCP.sql;
--@@CUST_FILE_LOAD_SUCC.sql;
--@@CUST_FILE_REC_CNT.sql;
--@@TRAN_FILE_LOAD_EXCP.sql;
--@@TRAN_FILE_LOAD_SUCC.sql;
--@@TRAN_FILE_REC_CNT.sql;



----@@MIGR_TRAN_DETL_EXCP_REP.prc;
--@@MIGR_DETAIL_EXCP_TRAN_LOAD_REP.prc;
--@@MIGR_TRAN_FILEWISE_LOAD_SUMRY.prc;
--@@MIGR_TRAN_FILE_LOAD_EXCP.prc;
--@@MIGR_TRAN_FILE_LOAD_SUCC.prc;
--@@MIGR_CUST_FILE_LOAD_SUCC.prc;
--@@MIGR_CUST_FILE_LOAD_EXCP.prc;
--@@MIGR_CUST_FILEWISE_LOAD_SUMRY.prc;
--@@MIGR_DETAIL_EXCP_CUST_LOAD_REP.prc;
----@@MIGR_CUST_CARD_DATA_SUMRY_REP.prc;
----@@MIGR_TRAN_DATA_SUMRY_REP.prc;
----@@MIGR_ACCT_SUCC_DETL_REP.prc;
----@@MIGR_CUST_SUCC_DETL_REP.prc;
----@@MIGR_CUST_EXCP_DETL_REP.prc;
--
--@@MIGR_ACCO_FILE_LOAD_EXCP.prc
--@@MIGR_ACCO_FILE_LOAD_SUCC.prc
--@@MIGR_ACCO_FILE_REC_CNT.prc
--@@MIGR_DETAIL_EXCP_ACCT_LOAD_REP.prc
----@@MIGR_DETAIL_EXCP_ACCT_REP.prc
