CREATE TABLE VMSCMS.MIGR_DET_ROLL_EXCP
(
MDR_FILE_NAME VARCHAR2(50),
MDR_MIGR_SEQNO NUMBER(5),
MDR_ACCT_NO    VARCHAR2(20),
MDR_REASON     VARCHAR2(500),
MDR_INS_DATE   DATE             DEFAULT SYSDATE
);