CREATE TABLE VMSCMS.MIGR_SUCC_LOG
(
  MSL_INST_CODE  NUMBER(5),
  MSL_FILE_NAME  VARCHAR2(50 BYTE),
  MSL_REC_NUMB   NUMBER(6),
  MSL_CARD_NUMB  VARCHAR2(20 BYTE),
  MSL_MESG       VARCHAR2(50 BYTE),
  MSL_USER       NUMBER(5),
  MSL_INS_DATE   DATE
);