CREATE TABLE VMSCMS.MIGR_UPDT_CTRL_DETL
(
  MUC_INST_CODE  NUMBER(5),
  MUC_PROD_CODE  VARCHAR2(20 BYTE),
  MUC_CARD_TYPE  NUMBER(5),
  MUC_BRCH_NUMB  VARCHAR2(20 BYTE),
  MUC_CTRL_NUMB  VARCHAR2(10 BYTE),
  MUC_CTRL_TYPE  VARCHAR2(10 BYTE),
  MUC_PROC_FLAG  VARCHAR2(1 BYTE),
  MUC_PROC_MESG  VARCHAR2(200 BYTE),
  MUC_INS_DATE   DATE,
  MUC_INS_USER   NUMBER(5)
);