CREATE TABLE VMSCMS.MIGR_SPPRT_FUNC_EXCP
(
  MSE_FILE_NAME      VARCHAR2(50 BYTE),
  MSE_RECORD_NUMBER  NUMBER(20),
  MSE_CARD_NO        VARCHAR2(19 BYTE),
  MSE_NEW_CARD_NO    VARCHAR2(19 BYTE),
  MSE_SPPRT_KEY      VARCHAR2(20 BYTE),
  MSE_TXN_CODE       VARCHAR2(15 BYTE),
  MSE_PROCESS_FLAG   VARCHAR2(1 BYTE),
  MSE_PROCESS_MSG    VARCHAR2(300 BYTE),
  MSE_INS_DATE       DATE
);