CREATE TABLE VMSCMS.MIGR_CUST_DATA_EXCP
(
  MCE_FILE_NAME      VARCHAR2(50 BYTE),
  MCE_RECORD_NUMBER  NUMBER(20),
  MCE_CARD_NUMBER    VARCHAR2(20 BYTE),
  MCE_PROCESS_FLAG   VARCHAR2(1 BYTE),
  MCE_PROCESS_MSG    CLOB,
  MCE_INS_DATE       DATE,
  MCE_SQL_ERR        CLOB
);