CREATE TABLE VMSCMS.MIGR_RPT_WRT_SUCC
(
  MRW_FILE_NAME  VARCHAR2(1000 BYTE),
  MRW_ERRMSG     VARCHAR2(200 BYTE),
  MRW_SUCC_CNT   NUMBER(20),
  MRW_ERR_CNT    NUMBER(20),
  MRW_SQLERRMSG  VARCHAR2(200 BYTE),
  MRW_PROCESS_DATE     DATE  DEFAULT SYSDATE,
  MRW_RPT_FILE     varchar2(100)
);