CREATE TABLE VMSCMS.MIGR_ERROR_LOG
(
  MEL_INST_CODE   NUMBER(3),
  MEL_FILE_NAME   VARCHAR2(50 BYTE),
  MEL_REC_NUMB    NUMBER(10),
  MEL_CARD_NUMB   VARCHAR2(20 BYTE),
  MEL_TYPE        VARCHAR2(40 BYTE),
  MEL_ERR_CODE    VARCHAR2(30 BYTE),
  MEL_ERR_DESC    VARCHAR2(50 BYTE),
  MEL_ERROR_MESG  VARCHAR2(3500 BYTE),
  MEL_INS_USER    NUMBER(5),
  MEL_INS_DATE    DATE
);