CREATE TABLE VMSCMS.MIGR_ACCT_DATA_EXCP
(
  MAE_FILE_NAME      VARCHAR2(50 BYTE),
  MAE_RECORD_NUMBER  NUMBER(20),
  MAE_ACCT_NUMBER    VARCHAR2(20 BYTE),
  MAE_PROCESS_FLAG   VARCHAR2(1 BYTE),
  MAE_PROCESS_MSG    VARCHAR2(4000 BYTE),
  MAE_INS_DATE       DATE,
  MAE_SQL_ERR        CLOB
);