CREATE TABLE VMSCMS.MIGR_CTRL_TABLE
(
  MCT_CTRL_CODE  VARCHAR2(25 BYTE),
  MCT_CTRL_KEY   VARCHAR2(20 BYTE),
  MCT_CTRL_NUMB  NUMBER(15),
  MCT_CTRL_DESC  VARCHAR2(50 BYTE),
  MCT_INS_USER   NUMBER(5),
  MCT_INS_DATE   DATE,
  MCT_LUPD_USER  NUMBER(5),
  MCT_LUPD_DATE  DATE,
  MCT_INST_CODE  NUMBER(10)
);