CREATE TABLE VMSCMS.MIGR_ROLL_COUNT
(
  MRC_TABLE_NAME  VARCHAR2(50 BYTE),
  MRC_SEL_CNT     NUMBER(20),
  MRC_DEL_CNT     NUMBER(20),
  MRC_MIGR_SEQNO  NUMBER(5),
  MRC_INS_DATE    DATE default sysdate
);