CREATE TABLE VMSCMS.MIGR_ACCT_DATA_TEMP
(
  MAD_FILE_NAME                VARCHAR2(50 BYTE),
  MAD_RECORD_NUMB              NUMBER(20),
  MAD_ACCT_NUMB                VARCHAR2(20 BYTE),
  MAD_BRANCH_ID                VARCHAR2(4 BYTE),
  MAD_ACCT_TYPE                VARCHAR2(2 BYTE),
  MAD_ACCT_STAT                VARCHAR2(2 BYTE),
  MAD_ACCTGEN_DATE             VARCHAR2(20 BYTE),
  MAD_AVAIL_BAL                VARCHAR2(21 BYTE),
  MAD_LEDG_BAL                 VARCHAR2(21 BYTE),
  MAD_SAVNG_ACCTREOPEN_DATE    VARCHAR2(20 BYTE),
  MAD_SAVNG_ACCT_INTEREST_AMT  VARCHAR2(31 BYTE),
  MAD_PROC_FLAG                CHAR(1 BYTE),
  MAD_SAVNGACCT_CLOSING_DATE   VARCHAR2(20 BYTE),
  MAD_MIGR_SEQNO			   number(5),
  MAD_ROLL_FLAG                varchar2(2) default 'N' 
);

ALTER TABLE VMSCMS.MIGR_ACCT_DATA_TEMP ADD (
  CONSTRAINT PK_MAD_ACCT_NUMB
 PRIMARY KEY
 (MAD_ACCT_NUMB));