SET FEEDBACK OFF
SPOOL $VMS_HOME/MIGRATION/ROLL_SEQNO_DETL.log

SELECT MFI_FILE_NAME FILE_NAME ,MFI_PROCESS_DATE PROCESS_DATE ,MFI_MIGR_SEQNO MIGR_SEQNO
FROM VMSCMS.MIGR_FILE_LOAD_INFO
WHERE MFI_PROCESS_STATUS ='OK'
order by MFI_MIGR_SEQNO;

SPOOL OFF;