CREATE TABLE vmscms.CMS_INST_PARAM_R16B2
as
SELECT * FROM vmscms.CMS_INST_PARAM WHERE 1 = 2;

CREATE TABLE vmscms.CMS_PROG_MAST_R16B2
as
SELECT * FROM vmscms.CMS_PROG_MAST WHERE 125=1; 

CREATE TABLE vmscms.PCMS_PROCESS_SCHEDULE_R16B2
as
SELECT * FROM vmscms.PCMS_PROCESS_SCHEDULE WHERE 1 = 2;

CREATE TABLE vmscms.VMS_CONFIG_QUERY_R16B2
as
SELECT * FROM vmscms.VMS_CONFIG_QUERY WHERE vcq_query_id ='CCF_CARDSTOCK_QRY';