ALTER TABLE  VMSCMS.CMS_PROD_CATTYPE_EBR ADD CPC_DORMANCY_ONCORPORATELOAD VARCHAR2(20); 
 
DECLARE
V_ERR_MSG  VARCHAR2(1000);
BEGIN

	VMSCMS.SP_CREATE_EDITIONING_VIEW('CMS_PROD_CATTYPE','CMS_PROD_CATTYPE_EBR',V_ERR_MSG);

	IF V_ERR_MSG <> 'OK' THEN  	
		DBMS_OUTPUT.PUT_LINE(V_ERR_MSG);
	END IF;
	
EXCEPTION

	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR WHILE CALLING SP_CREATE_EDITIONING_VIEW PROCEDURE '|| SUBSTR(SQLERRM,1,200));
END;
/



